export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';

export const PROJECT_DATA_REQUEST = 'PROJECT_DATA_REQUEST';
export const PROJECT_DATA_SUCCESS = 'PROJECT_DATA_SUCCESS';
export const PROJECT_DATA_FAILURE = 'PROJECT_DATA_FAILURE';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST ';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS ';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE ';



